import Navbar from "@/components/Navbar";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { getServerSession } from "next-auth";
import SessionProvider from "@/utils/SessionProvider";
import "bootstrap/dist/css/bootstrap.min.css";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Shiny Secure",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	const session = await getServerSession();
	return (
		<html lang='en'>
			<body>
				<body className={`${inter.className} pic`}>
					<SessionProvider session={session}>
						<div className='mx-auto max-w-5xl text-2xl gap-2 mb-10'>
							<Navbar />

							{children}
						</div>
						<Footer />
					</SessionProvider>
				</body>
			</body>
		</html>
	);
}
